/*This file was generated by NativeWind. Do not edit!*/
const { NativeWindStyleSheet: _NativeWindStyleSheet } = require('nativewind');
_NativeWindStyleSheet.create({
  styles: {
    '*': {
      borderTopColor: 'hsl(214.3, 31.8%, 91.4%)',
      borderRightColor: 'hsl(214.3, 31.8%, 91.4%)',
      borderBottomColor: 'hsl(214.3, 31.8%, 91.4%)',
      borderLeftColor: 'hsl(214.3, 31.8%, 91.4%)',
    },
    '': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    html: {
      lineHeight: 1.5,
      fontFamily: 'ui-sans-serif',
    },
    body: {
      backgroundColor: 'hsl(0, 0%, 0%)',
      color: 'hsl(222.2, 84%, 4.9%)',
    },
    hr: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    'abbr:where([title])': {
      textDecorationLine: 'underline',
      textDecorationColor: 'black',
      textDecorationStyle: 'dotted',
    },
    code: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    kbd: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    samp: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    pre: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    small: {
      fontSize: '80%',
    },
    sub: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    sup: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    button: {
      backgroundColor: 'transparent',
    },
    input: {
      opacity: 1,
      color: '#9ca3af',
    },
    optgroup: {
      fontFamily: 'inherit',
      fontSize: '100%',
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    select: {
      textTransform: 'none',
    },
    textarea: {
      opacity: 1,
      color: '#9ca3af',
    },
    "[type='button']": {
      backgroundColor: 'transparent',
    },
    "[type='reset']": {
      backgroundColor: 'transparent',
    },
    "[type='submit']": {
      backgroundColor: 'transparent',
    },
    ':-moz-ui-invalid': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'black',
      shadowOpacity: 1,
    },
    blockquote: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dl: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dd: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h1: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h2: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h3: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h4: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h5: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h6: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    figure: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    p: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    fieldset: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    legend: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ol: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ul: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    menu: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    dialog: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    img: {
      maxWidth: '100%',
    },
    video: {
      maxWidth: '100%',
    },
    '[hidden]': {
      display: 'none',
    },
    container: {
      width: '100%',
      marginRight: 'auto',
      marginLeft: 'auto',
    },
    'container@0': {
      maxWidth: 200,
    },
    'container@1': {
      maxWidth: 640,
    },
    'container@2': {
      maxWidth: 768,
    },
    'container@3': {
      maxWidth: 1024,
    },
    'container@4': {
      maxWidth: 1280,
    },
    'container@5': {
      maxWidth: 1536,
    },
    'ml-auto': {
      marginLeft: 'auto',
    },
    flex: {
      display: 'flex',
    },
    hidden: {
      display: 'none',
    },
    'flex-1': {
      flexGrow: 1,
      flexShrink: 1,
    },
    'flex-row': {
      flexDirection: 'row',
    },
    'items-center': {
      alignItems: 'center',
    },
    'justify-center': {
      justifyContent: 'center',
    },
    ':not([hidden])': {
      borderTopColor: 'rgba(156, 163, 175, 1)',
      borderRightColor: 'rgba(156, 163, 175, 1)',
      borderBottomColor: 'rgba(156, 163, 175, 1)',
      borderLeftColor: 'rgba(156, 163, 175, 1)',
    },
    'self-center': {
      alignSelf: 'center',
    },
    border: {
      borderTopWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
    },
    'bg-black': {
      backgroundColor: 'rgba(0, 0, 0, 1)',
    },
    'text-2xl': {
      fontSize: '1.5rem',
      lineHeight: '2rem',
    },
    'text-3xl': {
      fontSize: '1.875rem',
      lineHeight: '2.25rem',
    },
    'text-4xl': {
      fontSize: '2.25rem',
      lineHeight: '2.5rem',
    },
    'text-lg': {
      fontSize: '1.125rem',
      lineHeight: '1.75rem',
    },
    'text-xl': {
      fontSize: '1.25rem',
      lineHeight: '1.75rem',
    },
    'font-bold': {
      fontWeight: '700',
    },
    'text-gray-400': {
      color: 'rgba(156, 163, 175, 1)',
    },
    'text-green-600': {
      color: 'rgba(22, 163, 74, 1)',
    },
    'text-muted-foreground': {
      color: 'hsl(240, 5%, 65%)',
    },
    'text-white': {
      color: 'rgba(255, 255, 255, 1)',
    },
    underline: {
      textDecorationLine: 'underline',
    },
    'from@0': {
      opacity: 1,
    },
    'to@0': {
      opacity: 1,
    },
    'hover:text-primary:hover': {
      color: 'hsl(222.2, 47.4%, 11.2%)',
    },
  },
  atRules: {
    container: [
      [['media', '(min-width: 200px)']],
      [['media', '(min-width: 640px)']],
      [['media', '(min-width: 768px)']],
      [['media', '(min-width: 1024px)']],
      [['media', '(min-width: 1280px)']],
      [['media', '(min-width: 1536px)']],
    ],
    from: [[['keyframes', 'enter']]],
    to: [[['keyframes', 'exit']]],
  },
  topics: {
    container: ['width'],
  },
});
